"""Description of migration

Revision ID: 16cc19f980bb
Revises: 8a654437279b
Create Date: 2023-12-01 20:41:19.358986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cc19f980bb'
down_revision = '8a654437279b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.alter_column('saved_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=30), nullable=False))
        batch_op.alter_column('saved_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
