"""Add baught_at to Save table

Revision ID: 37e8dcb0a81c
Revises: 
Create Date: 2023-11-27 19:46:03.695742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e8dcb0a81c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baught_at', sa.String(length=40), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_unique_constraint(None, ['baught_at'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('baught_at')

    # ### end Alembic commands ###
