"""add bought_at to Save model

Revision ID: 8a654437279b
Revises: 37e8dcb0a81c
Create Date: 2023-12-01 13:27:30.588259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a654437279b'
down_revision = '37e8dcb0a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_save')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_save',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cash', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('saved_at', sa.DATETIME(), nullable=False),
    sa.Column('baught_at', sa.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baught_at', name='uq_save_baught_at'),
    sa.UniqueConstraint('username', name='uq_save_username')
    )
    # ### end Alembic commands ###
